import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Minus, CornerUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { usePikup, formatTime, type Verdict } from '@/lib/pikup';
export const Route=createFileRoute('/end-session')({head:()=>({meta:[{title:'Close your session — Pikup'},{name:'description',content:'Reflect on your intention and leave one next step for your future self.'},{property:'og:title',content:'Close your session — Pikup'},{property:'og:description',content:'An honest check-in and one intention for next time.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:EndSession});
function EndSession() {
 const {last,timer,elapsed,pause,save,ready}=usePikup(); const navigate=useNavigate(); const [verdict,setVerdict]=useState<Verdict|null>(null); const [worked,setWorked]=useState(''); const [intention,setIntention]=useState(''); const [saving,setSaving]=useState(false);
 useEffect(()=>{if(timer.startedAt) pause();},[timer.startedAt]);
 if(ready&&!timer.active) return <main className="page end-page"><h1 className="hand-title">A new session is waiting.</h1><Button asChild className="mt-6"><Link to="/"><ArrowLeft/>Back to my session</Link></Button></main>;
 return <main className="page end-page"><Button variant="link" asChild className="p-0 h-auto text-xs"><Link to="/"><ArrowLeft/>Back to my session</Link></Button><div className="flex justify-between items-center mt-7"><span className="eyebrow">A moment to reflect</span><span className="text-xs text-muted-foreground">{formatTime(elapsed).join(':')} of deep work</span></div><h1 className="hand-title mt-3">Leave a little intention.</h1><p className="text-sm text-muted-foreground mt-3">A note for your future self. Nothing more, nothing less.</p>
 <form className="mt-9" onSubmit={e=>{e.preventDefault();if(saving||!worked.trim()||!intention.trim()||(last&&!verdict))return;setSaving(true);save(worked.trim(),intention.trim(),last?verdict:null);navigate({to:'/'});}}>
 {last?<section><div className="note-label">Your last intention</div><blockquote className="end-intention">{last.intention}</blockquote><h2 className="text-sm font-medium">Did you work on this?</h2><div className="choice-grid" role="group" aria-label="Did you work on your last intention?">{([{id:'yes',label:'Yes',Icon:Check},{id:'partially',label:'Partially',Icon:Minus},{id:'no',label:'No',Icon:CornerUpRight}] as const).map(c=><Button type="button" key={c.id} variant="ghost" className="choice" aria-pressed={verdict===c.id} onClick={()=>setVerdict(c.id)}><c.Icon/>{c.label}</Button>)}</div><p className="text-xs text-muted-foreground mt-3">An honest answer is a good answer. Plans can change.</p></section>:<p className="hand text-2xl text-primary">Your first session. A lovely place to begin.</p>}
 <section className="form-section"><label htmlFor="worked" className="field-label">What did you work on this session?</label><textarea id="worked" className="note-field" placeholder="A few words about what you worked on…" value={worked} onChange={e=>setWorked(e.target.value)} required maxLength={200} rows={2}/><label htmlFor="intention" className="field-label mt-6">What’s the <strong>one thing</strong> you plan to work on next time?</label><textarea id="intention" className="note-field" placeholder="Next time, I intend to…" value={intention} onChange={e=>setIntention(e.target.value)} required maxLength={160} rows={2}/></section><div className="save-line"><span className="hand text-xl text-muted-foreground">Small and specific is enough.</span><Button type="submit" className="h-12 px-6" disabled={saving||!ready||!worked.trim()||!intention.trim()||Boolean(last&&!verdict)}>Save & close session<ArrowRight/></Button></div></form></main>;
}
