import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowLeft, Check, Lock, Pin } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Plant, Sticker, stickers } from '@/components/pikup-art';
import { Footer } from '@/components/pikup-shell';
import { usePikup } from '@/lib/pikup';
export const Route=createFileRoute('/weekly')({head:()=>({meta:[{title:'Your weekly garden — Pikup'},{name:'description',content:'Deep work and honest follow-through, side by side. Watch your project grow and collect this week’s stickers.'},{property:'og:title',content:'Your weekly garden — Pikup'},{property:'og:description',content:'A little growth, one intention at a time. See your week and pin your earned stickers.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Weekly});
function Weekly() {
 const {stats,week,pins,unlocked,togglePin}=usePikup(); const monday=new Date(`${week}T00:00:00`); const sunday=new Date(monday); sunday.setDate(sunday.getDate()+6);
 const dateLabel=`${monday.toLocaleDateString('en-US',{month:'short',day:'numeric'})} – ${sunday.toLocaleDateString('en-US',{month:'short',day:'numeric'})}`;
 return <main className="page"><Button variant="link" asChild className="p-0 h-auto text-xs"><Link to="/"><ArrowLeft/>Back to my session</Link></Button><div className="weekly-top mt-6"><div><div className="eyebrow">Your weekly garden</div><h1 className="hand-title mt-3">Progress, on purpose.</h1></div><span className="text-xs text-muted-foreground">{dateLabel} <span className="mx-2">·</span> A fresh week, every Monday</span></div>
 <div className="weekly-metrics"><section className="metric"><div className="eyebrow">Deep work this week</div><p className="metric-value">{stats.hours.toFixed(1)} <small>hrs</small></p><p className="text-xs text-muted-foreground">Time made for your project.</p></section><section className="metric"><div className="eyebrow">Follow-through this week</div><p className="metric-value">{stats.yes} <small>of</small> {stats.judged} <small>sessions</small></p><p className="text-xs text-muted-foreground">{stats.judged?`${Math.round(stats.yes/stats.judged*100)}% on track · “Yes” to your intention`:'On track · Your first check-in is still ahead.'}</p></section></div>
 <div className="growth-grid"><section className="garden-panel"><Plant growth={stats.yes} className="weekly-plant"/><h2 className="hand text-3xl">{stats.yes>=5?'A week in bloom.':stats.yes?'Roots down. Leaves up.':'Every intention starts a little seed.'}</h2><p className="text-xs text-muted-foreground mt-2">{stats.yes?'Your follow-through is helping this little plant grow.':'Your plant grows with each session on track.'}</p><div className="days">{['M','T','W','T','F','S','S'].map((label,i)=>{const date=new Date(monday);date.setDate(date.getDate()+i);const completed=stats.rows.some(s=>new Date(s.date).toDateString()===date.toDateString()&&s.verdict==='yes');return <div key={i} className="day"><span className={`day-dot ${completed?'completed':''}`} title={`${date.toLocaleDateString('en-US',{weekday:'long'})}: ${completed?'on track':'no on-track session yet'}`}>{completed&&<Check size={13}/>}</span><span>{label}</span></div>;})}</div></section>
 <section><div className="eyebrow mt-3">This week’s little keepsakes</div><h2 className="hand text-3xl mt-2">Earn a little. Pin a little.</h2><p className="text-xs text-muted-foreground mt-2">Fresh stickers each week. Your favorites live on your notebook.</p><div className="sticker-list">{stickers.map(item=>{const earned=unlocked.includes(item.id),pinned=pins.includes(item.id);return <div className="sticker-row" key={item.id}><Button variant="ghost" className={`sticker-button ${earned?'':'locked'}`} disabled={!earned} onClick={()=>togglePin(item.id)} aria-pressed={pinned} aria-label={`${pinned?'Unpin':'Pin'} ${item.name}`} title={earned?(pinned?'Unpin from your main screen':'Pin to your main screen'):item.detail}><Sticker id={item.id}/></Button><div><h3>{item.name}</h3><p>{item.detail}</p><p className="flex items-center gap-1 mt-2">{earned?<><Pin size={11}/>{pinned?'Pinned to your notebook':'Ready to pin'}</>:<><Lock size={10}/>Still growing toward this one</>}</p></div></div>;})}</div><p className="hand text-xl text-muted-foreground mt-7">A new week, a new chance to grow.</p></section></div><Footer/></main>;
}
